[GECO-23] configure OCR format through UI
diging/giles-eco-cassiopeia pull request #10
Opened 2017-04-21 17:11 UTC by snilapwa

2017-04-26 16:00 UTC, jdamerow requested changes

2017-04-26 16:00 UTC, jdamerow commented on cassiopeia/src/main/webapp/WEB-INF/views/admin/system_config.jsp
> +        <label> <form:checkbox path="createhOCR" /> Create hOCR
let's make that a drop down menu with options HOCR and Plain text

2017-04-26 16:00 UTC, jdamerow commented on cassiopeia/src/main/webapp/WEB-INF/views/admin/system_config.jsp
> +        <h3>Type of OCR Format</h3>
Header should be "OCR Settings"

2017-04-27 20:41 UTC, jdamerow requested changes

2017-04-27 20:41 UTC, jdamerow commented on cassiopeia/src/main/java/edu/asu/diging/gilesecosystem/cassiopeia/web/EditPropertiesController.java
> +        ocrTypeMap.put(hOCR, "HOCR");
no hardcoding of string!

2017-04-27 20:41 UTC, jdamerow commented on cassiopeia/src/main/java/edu/asu/diging/gilesecosystem/cassiopeia/web/EditPropertiesController.java
> +        model.addAttribute("selectedOCRType", page.getOCRType());
do you use that anywhere?

2017-04-27 21:01 UTC, snilapwa commented on cassiopeia/src/main/java/edu/asu/diging/gilesecosystem/cassiopeia/web/EditPropertiesController.java
> +        model.addAttribute("selectedOCRType", page.getOCRType());
yes, to set this value as selected value in dropdown when page loads

2017-04-27 21:25 UTC, snilapwa commented on cassiopeia/src/main/java/edu/asu/diging/gilesecosystem/cassiopeia/web/EditPropertiesController.java
> +        model.addAttribute("selectedOCRType", page.getOCRType());
I can use systemConfigPage for the same! removed extra parameter

2017-04-27 21:35 UTC, jdamerow approved these changes

2017-04-27 21:35 UTC, merged