[GECO-64] show version number in footer
diging/giles-eco-cassiopeia pull request #11
Opened 2017-05-01 23:17 UTC by snilapwa

2017-05-01 23:48 UTC, jdamerow requested changes

2017-05-01 23:48 UTC, jdamerow commented on cassiopeia/pom.xml
> +        <buildNumber></buildNumber>
this also needs the buildnumber plugin which I don't believe is included right now.

2017-05-02 16:50 UTC, snilapwa commented
updated with scm definition

2017-05-02 17:45 UTC, jdamerow commented
Please add buildNumber.properties to gitignore

2017-05-02 17:57 UTC, snilapwa commented
Updated gitignore

2017-05-02 17:59 UTC, jdamerow approved these changes

2017-05-02 17:59 UTC, merged